"""initial migration

Revision ID: 6c23174b5ed6
Revises: 
Create Date: 2025-05-12 17:30:32.847363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c23174b5ed6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_diet_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('daily_calorie_target', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('preferred_meal_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferred_meal_count')
        batch_op.drop_column('daily_calorie_target')
        batch_op.drop_column('preferred_diet_type')

    # ### end Alembic commands ###
