"""Add recipe enhancements

Revision ID: 7c2a44556a19
Revises: 6c23174b5ed6
Create Date: 2025-05-12 17:33:46.601200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2a44556a19'
down_revision = '6c23174b5ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('is_featured')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
